spring:
  application:
    name: "@project.name@"
  datasource:
    url: jdbc:h2:mem:myhexagon
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      
logging:
  level:
    root: INFO
    br.org.pessoal: INFO # DEBUG