spring:
  application:
    name: "@project.name@"

  datasource:
    url: jdbc:h2:mem:exception
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true